Repository abalabahaha/eris, pull requests merged in 2018-04, with the labels that each got.

#368 Added functions to allow voice channel leave without channelID (and fixed some related things)
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: enhancement, voice

#380 fix: OggOpusTransformer doesn't work with multiple streams
  lib/voice/streams/OggOpusTransformer.js
Labels: bug, voice

#376 Change how duplicate presences are detected
  lib/gateway/Shard.js
Labels: bug, enhancement

#378 Fix clean content for custom emotes and system messages
  lib/structures/Message.js
Labels: bug
