Repository abalabahaha/eris, pull requests merged in 2018-02, with the labels that each got.

#361 update editStatus docs
  lib/Client.js
Labels: docs

#363 Fix spotify presence updates not caching properly
  lib/gateway/Shard.js
Labels: bug

#364 Add Eris.VERSION
  index.js
Labels: enhancement
