Repository abalabahaha/eris, pull requests merged in 2018-08, with the labels that each got.

#408 Update to Node 8
  .eslintrc.yml
  lib/Client.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/errors/DiscordHTTPError.js
  lib/errors/DiscordRESTError.js
  lib/gateway/Shard.js
  lib/gateway/ShardManager.js
  lib/rest/RequestHandler.js
  lib/structures/Base.js
  lib/structures/Call.js
  lib/structures/CategoryChannel.js
  lib/structures/Channel.js
  lib/structures/ExtendedUser.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/GuildIntegration.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/Permission.js
  lib/structures/PermissionOverwrite.js
  lib/structures/PrivateChannel.js
  lib/structures/Relationship.js
  lib/structures/Role.js
  lib/structures/TextChannel.js
  lib/structures/UnavailableGuild.js
  lib/structures/User.js
  lib/structures/VoiceChannel.js
  lib/structures/VoiceState.js
  lib/util/Bucket.js
  lib/util/Collection.js
  lib/util/MultipartData.js
  lib/util/SequentialBucket.js
  lib/voice/Piper.js
  lib/voice/SharedStream.js
  lib/voice/VoiceConnection.js
  lib/voice/VoiceConnectionManager.js
  lib/voice/VoiceDataStream.js
  lib/voice/streams/BaseTransformer.js
  lib/voice/streams/DCAOpusTransformer.js
  lib/voice/streams/FFmpegDuplex.js
  lib/voice/streams/FFmpegOggTransformer.js
  lib/voice/streams/FFmpegPCMTransformer.js
  lib/voice/streams/OggOpusTransformer.js
  lib/voice/streams/PCMOpusTransformer.js
  lib/voice/streams/VolumeTransformer.js
  lib/voice/streams/WebmOpusTransformer.js
  package.json
Labels: enhancement

#399 Allow return from command hooks
  lib/command/Command.js
Labels: enhancement

#412 Fix docs for emoji endpoints
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord, docs

#414 Complete Command types and support for getBan, getGuildBan to TypeScript types
  index.d.ts
Labels: typings
