Repository abalabahaha/eris, pull requests merged in 2018-11, with the labels that each got.

#432 Add complete emoji and TextChannel#purge typings
  index.d.ts
Labels: typings

#433 Add function to get the vanity URL of a guild
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: enhancement

#435 Update required node version to 8
  package.json
Labels: bug

#434 Add the version constant
  index.d.ts
Labels: typings
