Repository abalabahaha/eris, pull requests merged in 2018-06, with the labels that each got.

#394 Use MessageContent instead of string in TS typings
  index.d.ts
Labels: bug

#393 Fix deprecation: Use symbol method for custom inspection
  lib/structures/Base.js
Labels: bug

#396 Updated for loops over Objects to check hasOwnProperty
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/errors/DiscordHTTPError.js
  lib/errors/DiscordRESTError.js
Labels: bug

#398 Allow guild-less invites for group DMs
  lib/structures/Invite.js
Labels: Discord, bug

#397 Add oldRole.mentionable doc entry to guildRoleUpdate
  lib/gateway/Shard.js
Labels: docs, farming
