Repository abalabahaha/eris, pull requests merged in 2019-10, with the labels that each got.

#536 make error properties writable
  lib/errors/DiscordHTTPError.js
  lib/errors/DiscordRESTError.js
Labels: bug

#532 Fix documentation typo's
  lib/Client.js
  lib/structures/Guild.js
Labels: docs

#541 d.ts: Add more properties to status activity
  index.d.ts
Labels: typings

#540 Fix eslint
  .eslintrc.yml
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/voice/VoiceConnection.js
  lib/voice/VoiceConnectionManager.js
  package.json
Labels: enhancement

#538 refactor command permission check
  lib/command/Command.js
Labels: enhancement

#550 Optimize Collection#random()
  lib/util/Collection.js
Labels: enhancement

#547 Custom reconnect
  index.d.ts
  lib/Client.js
Labels: enhancement

#549 Add eslint rules
  .eslintrc.yml
  examples/basicCommands.js
  examples/embed.js
  examples/pingpong.js
  examples/playFile.js
  examples/reactionButtons.js
  index.js
  lib/Client.js
  lib/Constants.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/gateway/Shard.js
  lib/rest/RequestHandler.js
  lib/structures/Base.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/User.js
  lib/voice/VoiceConnection.js
  lib/voice/streams/FFmpegDuplex.js
  package.json
Labels: enhancement

#552 Fix incorrect typings
  index.d.ts
  lib/structures/CategoryChannel.js
  lib/structures/Guild.js
  lib/structures/Message.js
Labels: bug, typings
