Repository abalabahaha/eris, pull requests merged in 2019-12, with the labels that each got.

#578 executeWebhook returns a bare object, not a Message object.
  lib/Client.js
Labels: bug

#580 Fix guildCreate docs
  lib/gateway/Shard.js
Labels: docs, typo

#581 Add curly rule
  .eslintrc.yml
  lib/structures/ExtendedUser.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/Role.js
  lib/structures/TextChannel.js
  lib/structures/User.js
  lib/structures/VoiceChannel.js
Labels: enhancement

#577 Intellisense Support
  package.json
Labels: enhancement

#583 Add support for self_stream field on voice state
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/VoiceState.js
Labels: Discord

#576 Promisified Guild#fetchAllMembers
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/Guild.js
Labels: enhancement

#593 Make IP discovery port parsing use big endian
  lib/voice/VoiceConnection.js
Labels: Discord, bug
