Repository abalabahaha/eris, pull requests merged in 2019-08, with the labels that each got.

#515 missing "deleteMessages" function on TextChannel type declaration
  index.d.ts
Labels: typings

#511 Update `defaultAvatar` calculation
  lib/Constants.js
  lib/structures/User.js
Labels: Discord

#516 Add stream perm
  lib/Constants.js
Labels: Discord

#505 splashURL/bannerURL use user given settings
  lib/Client.js
  lib/structures/Guild.js
Labels: enhancement

#513 Guild Subscriptions
  lib/Client.js
  lib/gateway/Shard.js
Labels: Discord

#518 Handle voice connection error event
  lib/voice/VoiceConnectionManager.js
Labels: bug

#514 Adds support for channel following and messageCreate type 12.
  lib/Constants.js
  lib/structures/Message.js
Labels: Discord

#522 Fixed return value for registerCommand
  index.d.ts
Labels: typings
