Repository abalabahaha/eris, pull requests merged in 2019-11, with the labels that each got.

#553 TypeScript: Make reconnectAttempts/Delay optional.
  index.d.ts
Labels: bug, typings

#548 reduce memory usage of voice states
  lib/structures/Guild.js
  lib/structures/Member.js
Labels: enhancement

#555 Prevent Member.activities to be overriden by undefined values
  lib/structures/Member.js
Labels: bug

#556 typings fixes
  index.d.ts
Labels: typings

#558 Typings File Enhancements
  .eslintrc.ts.yml
  index.d.ts
Labels: typings

#561 Code consistency
  index.d.ts
Labels: typings

#560 Fix typings typos
  index.d.ts
  lib/structures/GuildChannel.js
Labels: typings

#562 Adds support for new audit log events
  index.d.ts
  lib/Constants.js
  lib/structures/GuildAuditLogEntry.js
Labels: Discord

#566 change category.channels to getter
  lib/gateway/Shard.js
  lib/structures/CategoryChannel.js
  lib/structures/Guild.js
Labels: enhancement

#565 Channel.from()
  lib/Client.js
  lib/structures/Channel.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/NewsChannel.js
  lib/structures/StoreChannel.js
  lib/structures/TextChannel.js
Labels: enhancement

#568 Switch ternary to if statement to prevent reassigning on <structure>.update
  lib/structures/ExtendedUser.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/Role.js
  lib/structures/TextChannel.js
  lib/structures/User.js
  lib/structures/VoiceChannel.js
Labels: enhancement

#567 Document flags for editMessage
  index.d.ts
  lib/Client.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord, docs

#563 Speed up resume attempts
  lib/gateway/Shard.js
  lib/gateway/ShardManager.js
Labels: enhancement

#571 Change deprecated arguments syntax to rest parameters
  lib/gateway/Shard.js
Labels: enhancement

#574 Fixes not passing client in Channel.from
  lib/gateway/Shard.js
Labels: bug

#573 allow null for member.edit({channeID: null})
  index.d.ts
Labels: bug

#569 Adds new constants and unify Constants usage
  index.d.ts
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Channel.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/User.js
  lib/voice/VoiceConnection.js
Labels: enhancement

#570 reformat toJSON
  index.d.ts
  lib/Client.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/gateway/Shard.js
  lib/gateway/ShardManager.js
  lib/rest/RequestHandler.js
  lib/structures/Base.js
  lib/structures/Call.js
  lib/structures/CategoryChannel.js
  lib/structures/Channel.js
  lib/structures/ExtendedUser.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/GuildIntegration.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/Permission.js
  lib/structures/PermissionOverwrite.js
  lib/structures/PrivateChannel.js
  lib/structures/Relationship.js
  lib/structures/Role.js
  lib/structures/TextChannel.js
  lib/structures/UnavailableGuild.js
  lib/structures/User.js
  lib/structures/VoiceChannel.js
  lib/structures/VoiceState.js
  lib/util/Collection.js
  lib/voice/VoiceConnection.js
  lib/voice/VoiceConnectionManager.js
Labels: enhancement

#575 Fix EventListener Typings And Adds store and news channel typings
  index.d.ts
Labels: enhancement, typings
