Repository abalabahaha/eris, pull requests merged in 2019-02, with the labels that each got.

#449 Member class updates
  lib/gateway/Shard.js
  lib/structures/Member.js
Labels: Discord, enhancement

#444 fix maximum avatar size threshold (1024 -> 2048)
  lib/Client.js
  lib/Constants.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/User.js
Labels: bug

#442 Add sort(), reduce(), some(), every() to Collection
  index.d.ts
  lib/util/Collection.js
Labels: enhancement

#462 Iterate over values instead on for loops
  lib/gateway/ShardManager.js
Labels: bug
