Repository abalabahaha/eris, pull requests merged in 2019-05, with the labels that each got.

#480 Add support for guild `explicitContentFilter` in editGuild
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#487 Fix seedVoiceConnections
  lib/structures/Guild.js
Labels: bug

#485 Ignore duplicate spaces between command args
  lib/command/CommandClient.js
Labels: enhancement

#488 Minor code improvements
  lib/Client.js
  lib/command/CommandClient.js
Labels: enhancement
