Repository abalabahaha/eris, pull requests merged in 2019-09, with the labels that each got.

#525 Added lastPinTimestamp property to TextChannel
  index.d.ts
Labels: typings

#520 Adds stream to Permissions.all, and Permissions.allVoice.
  lib/Constants.js
Labels: bug

#529 fix function context for request timeout
  lib/rest/RequestHandler.js
Labels: bug

#530 Fix Collection#reduce() documentation
  index.d.ts
  lib/util/Collection.js
Labels: docs, typings
