Repository abalabahaha/eris, pull requests merged in 2019-07, with the labels that each got.

#495 Add nitro boost message types and other guild properties
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/Member.js
  lib/structures/Message.js
Labels: Discord

#502 Move default Client#on event declaration
  index.d.ts
Labels: typings

#501 Guild#iconURL/dynamicIconURL use GIF when icon is animated.
  lib/structures/Guild.js
Labels: Discord

#503 Fix for upcoming change to Discord voice nodes
  lib/Constants.js
  lib/voice/VoiceConnection.js
Labels: Discord

#507 Code/style fixes
  index.d.ts
  lib/rest/RequestHandler.js
  lib/structures/Base.js
  lib/structures/ExtendedUser.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/Permission.js
  lib/structures/Relationship.js
  lib/structures/User.js
Labels: enhancement
