Repository abalabahaha/eris, pull requests merged in 2019-04, with the labels that each got.

#476 Add client property to Shard type
  index.d.ts
Labels: typings

#475 Add support for guild banner
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/Guild.js
Labels: Discord

#472 NewsChannel (type 5) Support
  index.js
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/Message.js
  lib/structures/NewsChannel.js
  lib/structures/TextChannel.js
Labels: Discord, bug, enhancement

#474 Added support for Node HTTP(S) Agent
  index.d.ts
  lib/Client.js
  lib/rest/RequestHandler.js
Labels: enhancement
