Repository abalabahaha/eris, pull requests merged in 2020-05, with the labels that each got.

#650 Fix linting error
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Base.js
  lib/structures/Message.js
Labels: typo

#926 Member: default data.id to data.user.id when nonexistent
  lib/structures/Member.js
Labels: bug

#937 Guild embed is deprecated in favor of guild widget
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: Discord

#920 Support for withCount field for GUILD endpoint
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#936 Support for guild/members/search members endpoint
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: enhancement

#934 Add support for include_roles in guild prune
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#935 Fix MESSAGE_REACTION_REMOVE_ALL and MESSAGE_REACTION_REMOVE_EMOJI
  lib/gateway/Shard.js
Labels: bug

#942 Remove default status in Members
  index.d.ts
  lib/structures/Member.js
Labels: Discord, enhancement

#933 Optional auth for execWebhook
  index.d.ts
  lib/Client.js
Labels: Discord

#949 Stop error when using any TextableChannel methods returning Message
  index.d.ts
Labels: typings

#952 Removing member logic from MESSAGE_REACTION_REMOVE
  lib/gateway/Shard.js
Labels: bug

#947 Fix broken ratelimiter
  lib/rest/RequestHandler.js
  lib/util/SequentialBucket.js
Labels: bug

#903 expose maxVideoChannelUsers in Guild
  index.d.ts
  lib/structures/Guild.js
Labels: Discord
