Repository abalabahaha/eris, pull requests merged in 2020-02, with the labels that each got.

#625 Adds inviteCreate and inviteDelete events
  .eslintrc.yml
  index.d.ts
  lib/gateway/Shard.js
Labels: Discord

#630 store channels are invitable
  index.d.ts
Labels: typings

#632 remove optional
  index.d.ts
  lib/structures/VoiceChannel.js
Labels: docs, typings

#638 clarify docs for temporary membership invites
  lib/Client.js
  lib/structures/Invite.js
  lib/structures/TextChannel.js
  lib/structures/VoiceChannel.js
Labels: docs

#639 break out message content type
  index.d.ts
Labels: typings

#631 Delete single reaction
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord, enhancement

#641 Improve documentation for reactionRemoveAll
  lib/gateway/Shard.js
Labels: docs, typo
