Repository abalabahaha/eris, pull requests merged in 2020-01, with the labels that each got.

#603 Improved ESM Support
  esm.mjs
  package.json
Labels: enhancement

#599 Added `4` as an option for `Activity#type`
  index.d.ts
Labels: typings

#598 add activities and clientStatus to OldPresence type
  index.d.ts
  lib/structures/Member.js
Labels: docs, typings

#597 Added bannerURL/splashURL typings
  index.d.ts
Labels: bug, typings

#588 Fix Client#createGuild() bug where shard was undefined
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
Labels: bug

#594 OldGuildChannel missing userLimit
  index.d.ts
Labels: bug

#606 ClientOptions.guildSubscriptions
  index.d.ts
Labels: typings

#608 Property Message#pinned was missing
  index.d.ts
Labels: typings

#618 Break out embed properties and reformat options
  index.d.ts
Labels: typings

#621 add type parameter to Message
  index.d.ts
Labels: typings

#624 Remove presence duplicate check
  lib/gateway/Shard.js
Labels: Discord, enhancement

#612 Fix PCM decoding that break by shared opus instance
  index.d.ts
  lib/Constants.js
  lib/util/Opus.js
  lib/voice/Piper.js
  lib/voice/SharedStream.js
  lib/voice/VoiceConnection.js
  lib/voice/streams/PCMOpusTransformer.js
Labels: bug

#619 Fix voiceChannelLeave race condition
  lib/gateway/Shard.js
Labels: bug

#613 fixes error happening on getRESTGuildMember
  lib/structures/Member.js
Labels: bug

#611 fix uncached role delete
  lib/gateway/Shard.js
Labels: bug

#620 Add Message#webhookID
  index.d.ts
  lib/structures/Message.js
Labels: Discord

#626 Convert all Message<this> to Message for now
  index.d.ts
Labels: bug, typings

#617 Add guildID prop to Message
  index.d.ts
  lib/structures/Message.js
Labels: enhancement

#623 Simplify image handling
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/User.js
Labels: enhancement

#622 Expose Channel.client
  index.d.ts
  lib/structures/Channel.js
  lib/structures/GroupChannel.js
  lib/structures/GuildChannel.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
  lib/structures/VoiceChannel.js
Labels: enhancement

#615 clean up presence types
  index.d.ts
Labels: typings

#629 Clean channel types
  index.d.ts
Labels: typings
