Repository abalabahaha/eris, pull requests merged in 2020-11, with the labels that each got.

#1005 Correct reason property removal
  lib/rest/RequestHandler.js
Labels: bug

#1028 Fix administrator permission not overriding other permissions for @everyone role
  lib/structures/Guild.js
Labels: bug

#1055 Mark avatar as being optional when creating webhooks
  index.d.ts
  lib/Client.js
  lib/structures/TextChannel.js
Labels: docs, typings

#1059 Add member to typingStart event
  index.d.ts
  lib/gateway/Shard.js
Labels: enhancement

#1066 Use ts-ignore
  index.d.ts
Labels: typings

#1068 Fix types for Message.reactions
  index.d.ts
  lib/structures/Message.js
Labels: docs, typings

#1067 Add System Channel flags
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/Guild.js
Labels: Discord

#1069 Inline replies
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord

#1078 Add support for Guild Templates
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
  lib/structures/GuildTemplate.js
Labels: Discord

#1080 JSDoc consistency
  lib/Client.js
  lib/structures/Guild.js
  lib/voice/SharedStream.js
Labels: docs

#1081 Guild missing properties
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/Guild.js
  lib/structures/GuildPreview.js
Labels: bug, docs, typings

#1083 Capture more custom inspect locations
  lib/gateway/Shard.js
  lib/rest/RequestHandler.js
  lib/util/BrowserWebSocket.js
  lib/util/Bucket.js
  lib/util/SequentialBucket.js
  lib/voice/Piper.js
  lib/voice/SharedStream.js
  lib/voice/VoiceConnection.js
  lib/voice/streams/BaseTransformer.js
  lib/voice/streams/FFmpegDuplex.js
Labels: enhancement

#1054 Redo invite to allow for non strict compilation (and other doc stuff)
  index.d.ts
Labels: bug, typings

#1015 Add Discovery
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: enhancement
