Repository abalabahaha/eris, pull requests merged in 2020-08, with the labels that each got.

#964 Command Client: Transport message and error to errorMessage
  lib/command/CommandClient.js
Labels: bug

#970 Encapsulate Textable channels in relevant interfaces
  index.d.ts
Labels: typings

#979 remove bot token from debug event
  lib/gateway/Shard.js
Labels: enhancement

#971 use proper function signature
  index.d.ts
Labels: typings

#973 Update the user object when using cached user on message create
  lib/structures/Message.js
Labels: bug

#974 Command: check cooldown first
  lib/command/Command.js
Labels: enhancement

#978 Fix "removeMessageReactionEmoji" on Message
  index.d.ts
  lib/structures/Message.js
Labels: bug

#981 Corrections for several typings
  index.d.ts
Labels: typings

#972 Fix typo in User docs
  lib/structures/User.js
Labels: docs, typo

#959 Add a getter for message links to the Message class
  index.d.ts
  lib/rest/Endpoints.js
  lib/structures/Message.js
Labels: enhancement

#977 Fix toJSON for ShardManager
  lib/gateway/ShardManager.js
Labels: bug

#985 Add GuildID property to message at reaction add/remove
  index.d.ts
  lib/gateway/Shard.js
Labels: enhancement

#975 Fix GuildPreview
  index.d.ts
  lib/rest/Endpoints.js
  lib/structures/Guild.js
  lib/structures/GuildPreview.js
Labels: bug, enhancement

#963 Member on messageReactionAdd
  index.d.ts
  lib/gateway/Shard.js
Labels: enhancement
