Repository abalabahaha/eris, pull requests merged in 2020-04, with the labels that each got.

#651 Correctly document all USER ACCOUNT methods
  lib/Client.js
  lib/structures/GroupChannel.js
  lib/structures/PrivateChannel.js
  lib/structures/Relationship.js
  lib/structures/User.js
Labels: docs

#669 Missing reason parameter in TextChannel.deleteMessages and purgeChannel
  index.d.ts
  lib/Client.js
  lib/structures/TextChannel.js
Labels: bug

#671 The bot gateway returns a session_start_limit object, and can be useful.
  index.d.ts
Labels: typings

#616 Intent Support
  examples/intent.js
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/util/Bucket.js
Labels: Discord, postponed

#672 Fix reaction events when channel not cached
  lib/gateway/Shard.js
Labels: bug

#895 fix Permission not being required for createRole
  lib/Client.js
Labels: bug

#899 Add missing jsdoc for Guild getters
  lib/structures/Guild.js
Labels: docs

#900 Max image size is 4096. Image format can be jpeg
  index.d.ts
  lib/Constants.js
Labels: Discord

#902 allowedMentions in editMessage
  lib/Client.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord

#901 Add support for crossposting messages
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Message.js
  lib/structures/NewsChannel.js
Labels: Discord

#897 Add publicFlags on user and the needed USER_FLAGS
  index.d.ts
  lib/Constants.js
  lib/structures/User.js
Labels: Discord

#917 Fix Message#crosspost
  lib/structures/Message.js
Labels: bug

#908 Fix a crash caused by trying to delete opus instance on opusOnly connection
  lib/voice/VoiceConnection.js
Labels: bug

#919 Missing methods in typings and documentation fix
  index.d.ts
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/User.js
Labels: docs, typings

#916 rawREST event
  index.d.ts
  lib/rest/RequestHandler.js
Labels: enhancement

#912 fixes #911 allowedMentions.users to work w/o *.roles
  lib/Client.js
Labels: bug

#906 Add support for GuildPreview endpoint
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/GuildPreview.js
Labels: Discord

#905 Specifies type of message in channel#messages.
  index.d.ts
Labels: typings

#904 Fix docs and typings for MESSAGE_REACTION_ADD and MESSAGE_REACTION_REMOVE events
  index.d.ts
  lib/gateway/Shard.js
Labels: docs, typings

#667 Add ms precision ratelimit
  lib/rest/RequestHandler.js
Labels: enhancement

#610 Add missing properties to Invite typings & Invite class
  index.d.ts
  lib/structures/Invite.js
Labels: enhancement
