Repository abalabahaha/eris, pull requests merged in 2021-11, with the labels that each got.

#1293 premiumProgressBarEnabled & nullable maxPresences
  index.d.ts
  lib/structures/Guild.js
Labels: Discord

#1290 Prevent heartbeat during identify
  index.d.ts
  lib/gateway/Shard.js
Labels: bug, hacktoberfest-accepted

#1229 Use "const" over "var" in README
  .eslintrc.yml
  README.md
Labels: farming, docs

#1269 Use new VoiceConnection send function in SharedStream
  lib/voice/SharedStream.js
Labels: bug, voice

#1233 Fix voiceState.selfStream when user stops streaming
  lib/gateway/Shard.js
Labels: bug, Discord

#1279 Discord API v9
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Base.js
  lib/structures/Channel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/NewsThreadChannel.js
  lib/structures/PrivateChannel.js
  lib/structures/PrivateThreadChannel.js
  lib/structures/PublicThreadChannel.js
  lib/structures/StageChannel.js
  lib/structures/StageInstance.js
  lib/structures/TextChannel.js
  lib/structures/ThreadChannel.js
  lib/structures/ThreadMember.js
Labels: Discord, hacktoberfest-accepted

#1295 Fix CommandInteraction and rawWS deep reference editing
  lib/structures/CommandInteraction.js
Labels: bug

#1271 Add, update, reorganize Constants
  index.d.ts
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/ThreadMember.js
  lib/voice/VoiceConnection.js
Labels: enhancement

#1205 Add target options for createInvite
  index.d.ts
  lib/Client.js
  lib/structures/Invite.js
Labels: Discord

#1292 Interactions MinMax
  index.d.ts
Labels: Discord, typings

#1277 Make shard ID optional for some events
  index.d.ts
  lib/Constants.js
Labels: typings

#1297 fix(docs): fix JSDoc complaints
  lib/Constants.js
  lib/structures/AutocompleteInteraction.js
  lib/structures/CommandInteraction.js
  lib/structures/UnknownInteraction.js
Labels: bug, docs

#1299 fix(typings): normalize Textable, fix deprecations
  index.d.ts
  lib/structures/ThreadChannel.js
Labels: bug, typings

#1301 fix(structs): fix incorrect thread method references
  lib/structures/Guild.js
  lib/structures/Message.js
Labels: bug

#1302 fix(voice): properly ignore non-voice packets
  lib/voice/VoiceConnection.js
Labels: bug, voice

#1267 feat(rest): add separate ratelimit for messages <=10s old
  lib/rest/RequestHandler.js
Labels: enhancement, Discord

#1287 fix(rest): combine routes for GET /guilds/:id/channels
  lib/rest/RequestHandler.js
Labels: bug, Discord, hacktoberfest-accepted
