Repository abalabahaha/eris, pull requests merged in 2021-07, with the labels that each got.

#1198 Fix message flags not being updated in cache
  lib/structures/Message.js
Labels: bug

#1226 Fix getMessages before & after option not being passed when trying to fetch 100 messages at once
  lib/Client.js
Labels: bug

#1225 Add getEmojiGuild to TS docs
  index.d.ts
Labels: typings

#1223 Bump ws from 7.2.1 to 7.4.6
  package.json
Labels: farming

#1209 Fix incorrect Channel constructor types
  index.d.ts
Labels: typings

#1199 Change hyperlink text
  README.md
Labels: farming

#1215 Document audit log unknown
  index.d.ts
Labels: typings

#1204 add certified moderator flag
  index.d.ts
  lib/Constants.js
Labels: Discord

#1235 Update user flag names
  index.d.ts
  lib/Constants.js
Labels: Discord

#1236 Make purgeChannel use getMessages options
  lib/Client.js
Labels: enhancement

#1237 Update sticker properties
  index.d.ts
  lib/structures/Message.js
Labels: Discord

#1202 Document disconnecting members from vc better
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/Member.js
Labels: docs

#1241 Fixing GUILD_TEMPLATE endpoint
  lib/rest/Endpoints.js
Labels: bug

#1207 Deprecate guild.nsfw in favour of nsfwLevel
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/Guild.js
Labels: Discord

#1224 Allow passing a plain object to permissionsOf
  index.d.ts
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
Labels: enhancement

#1239 Support sending multiple embeds
  index.d.ts
  lib/Client.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord

#1038 REST V8, Gateway v8
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/command/CommandClient.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/rest/RequestHandler.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/GuildIntegration.js
  lib/structures/Member.js
  lib/structures/PermissionOverwrite.js
  lib/structures/Relationship.js
  lib/structures/Role.js
Labels: Discord

#1217 Fix possibly undefined member in voiceStateUpdate
  index.d.ts
  lib/gateway/Shard.js
Labels: bug
