Repository abalabahaha/eris, pull requests merged in 2021-03, with the labels that each got.

#1136 Add missing Guild Audit Log properties
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#1126 Add competing status in types
  index.d.ts
  lib/Client.js
Labels: Discord

#1090 More specific type on permission "json" and "has"
  index.d.ts
Labels: typings

#1096 Add available property to Emoji
  index.d.ts
Labels: typings

#1107 Correct documentation for subcommandAliases
  index.d.ts
  lib/command/Command.js
Labels: typings

#1099 wrong typing on inline replies
  index.d.ts
Labels: typings

#1105 Fix clarification in updateVoiceState
  lib/voice/VoiceConnection.js
Labels: docs

#1097 Fix some typescript mistakes
  index.d.ts
  lib/Client.js
  lib/voice/VoiceConnection.js
Labels: docs, typings

#1106 Type this for instances which use itself
  index.d.ts
  package.json
Labels: typings

#1104 Correct toJSON locations
  lib/Client.js
  lib/structures/Guild.js
Labels: bug

#1060 Support editing/deleting webhook messages
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Message.js
Labels: Discord

#1110 Remove checking of "nsfw" and "nsfw-" in channel name.
  lib/structures/GuildChannel.js
Labels: Discord

#1103 Expose application info on ready
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
Labels: Discord

#1111 Show non deprecated overloads by default
  index.d.ts
Labels: typings

#1112 Added attachment image properties
  index.d.ts
Labels: typings

#1098 Update member cache on messageReactionAdd
  lib/gateway/Shard.js
Labels: enhancement

#1115 Added flags property to OldMessage
  index.d.ts
  lib/gateway/Shard.js
Labels: bug

#1045 no channel cache reliance on Message* events
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/Message.js
Labels: enhancement

#1037 expose welcomeScreen on Invite
  index.d.ts
  lib/structures/Guild.js
Labels: Discord

#1036 Update documentation for options.auth
  lib/Client.js
Labels: docs

#1035 expose selfVideo in VoiceState
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/VoiceState.js
Labels: Discord

#1032 toJSON consistency
  lib/structures/Base.js
  lib/structures/Guild.js
  lib/structures/GuildPreview.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/User.js
  lib/structures/VoiceState.js
Labels: bug

#1034 document lockPermissions and parentID for editChannelPosition
  index.d.ts
  lib/Client.js
  lib/structures/GuildChannel.js
Labels: Discord

#1033 Document discovery_splash and features in editGuild
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#1031 document and expose discord application (bot / webhooks)
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/GuildIntegration.js
Labels: Discord

#1025 gateway shard: check undocumented field before accessing
  lib/gateway/Shard.js
Labels: bug

#1150 Fix welcome screen in Guild structure
  lib/structures/Guild.js
Labels: bug

#1149 Add premiumType
  index.d.ts
  lib/structures/User.js
Labels: Discord
