Repository abalabahaha/eris, pull requests merged in 2021-10, with the labels that each got.

#1238 Add support for user banners
  index.d.ts
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildPreview.js
  lib/structures/Member.js
  lib/structures/User.js
Labels: Discord

#1258 Ability to manage stickers, guildStickersUpdate and Guild#stickers
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/rest/RequestHandler.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/util/MultipartData.js
Labels: Discord

#1288 Adding missing message activity flags
  index.d.ts
  lib/Constants.js
Labels: Discord, hacktoberfest-accepted

#1280 Support Interactions
  .gitignore
  esm.mjs
  examples/applicationCommands.js
  examples/components.js
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/AutocompleteInteraction.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/Guild.js
  lib/structures/Interaction.js
  lib/structures/Message.js
  lib/structures/PingInteraction.js
  lib/structures/UnknownInteraction.js
Labels: hacktoberfest-accepted

#1254 Tweak eslint.ts
  .eslintrc.ts.yml
  index.d.ts
Labels: farming
