Repository abalabahaha/eris, pull requests merged in 2021-01, with the labels that each got.

#1117 Fix Guild.editWidget (atm it just fetches the widget)
  lib/structures/Guild.js
Labels: bug

#1120 fix replies in dm channels
  lib/structures/Message.js
Labels: bug

#1122 Corrected some typings.
  index.d.ts
Labels: typings

#1093 Fix typo from #972
  lib/structures/User.js
Labels: typo
