Repository abalabahaha/eris, pull requests merged in 2021-04, with the labels that each got.

#1159 Account for undefined message content on message update
  lib/structures/Message.js
Labels: bug

#1161 Expose RTC region
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/GuildChannel.js
  lib/structures/VoiceChannel.js
Labels: Discord

#1160 Expose message type 22
  index.d.ts
  lib/Constants.js
  lib/structures/Message.js
Labels: Discord

#1157 Expose video quality mode
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/GuildChannel.js
  lib/structures/VoiceChannel.js
Labels: Discord

#1154 Full coverage of Stage Channels
  index.d.ts
  lib/gateway/Shard.js
Labels: Discord, typings

#1156 Correct systemChannelFlags typings
  index.d.ts
Labels: bug, typings

#1163 Add support for editing files in webhooks
  index.d.ts
  lib/Client.js
  lib/structures/Message.js
Labels: Discord

#1162 Fix decode error when using sodium-native
  lib/voice/VoiceConnection.js
Labels: bug

#1130 Incorrect Usage Embed Fix
  index.d.ts
  lib/command/Command.js
Labels: bug

#1166 Add editVanity method
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#1167 Add `interaction` prop to Messages
  index.d.ts
  lib/structures/Message.js
Labels: Discord

#1175 Missing bigint in allow/deny for Overwrite interface
  index.d.ts
Labels: typings

#1170 Tidy up typings
  index.d.ts
Labels: typings

#1177 Expose Guild#nsfw
  index.d.ts
  lib/gateway/Shard.js
  lib/structures/Guild.js
Labels: Discord

#1155 REST endpoints for stage channels
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: Discord

#1185 Undocument Client.token
  lib/Client.js
Labels: docs

#1184 Fix Permission constructor typings
  index.d.ts
Labels: typings

#1183 Remove Sticker preview_asset typings
  index.d.ts
Labels: typings

#1182 Support getWebhookMessage()
  index.d.ts
  lib/Client.js
Labels: Discord

#1179 Support welcome screen endpoints
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: Discord

#1176 Fix voice server update endpoint handling
  lib/voice/VoiceConnection.js
Labels: bug

#1187 Move to content.messageReference
  index.d.ts
  lib/Client.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord
