Repository abalabahaha/eris, pull requests merged in 2021-08, with the labels that each got.

#1255 Require ClientOptions in Eris constructor
  index.d.ts
Labels: typings

#1248 fix some jsdoc for editRole & createRole
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: docs

#1249 fix permissions: Value "undefined" is not int for editRole & createRole
  lib/Client.js
Labels: bug

#1212 Type guild features as actual values
  index.d.ts
Labels: typings

#1213 Expose audit log events 83-85
  index.d.ts
  lib/Constants.js
  lib/structures/GuildAuditLogEntry.js
Labels: Discord

#1256 Improve v8 ratelimit handling
  lib/rest/RequestHandler.js
Labels: bug

#1257 Update permission flag names to match Discord & update guildEmojisAndStickers intent name
  index.d.ts
  lib/Constants.js
Labels: Discord

#1261 Warn when invalid intent is supplied
  lib/Client.js
Labels: enhancement, farming

#1189 Expose components
  index.d.ts
  lib/Client.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
Labels: Discord

#1250 Add decodeReasons to RequestHandlerOptions typings
  index.d.ts
Labels: typings

#1219 Support per-guild avatars
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
  lib/structures/Member.js
Labels: Discord

#1242 Better types for events
  index.d.ts
Labels: typings

#1195 Enhancements for VoiceChannel join methods
  index.d.ts
  lib/Client.js
  lib/structures/VoiceChannel.js
Labels: enhancement, Discord
