Repository abalabahaha/eris, pull requests merged in 2022-05, with the labels that each got.

#1351 fix(typings): outdated `EventListeners.channelCreate` type
  index.d.ts
Labels: typings

#1355 fix(constants): Include manageThreads, manageEvents in Permissions.all
  index.d.ts
  lib/Constants.js
Labels: bug

#1366 fix(userUpdate): Uncached users throwing undefined
  lib/gateway/Shard.js
Labels: bug

#1373 fix(deleteMessages): Properly pass through `reason` option
  lib/Client.js
Labels: bug

#1375 docs(Voice state): Update to new caveat URL
  lib/Client.js
  lib/structures/Guild.js
Labels: farming, docs

#1359 fix(Message): Jumplink throwing on DM messages
  lib/structures/Message.js
Labels: bug

#1374 feat(Permissions): Add bigint support for perm check
  index.d.ts
  lib/structures/Permission.js
Labels: enhancement
