Repository abalabahaha/eris, pull requests merged in 2022-06, with the labels that each got.

#1298 Text in Guild Voice Channels
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/Invite.js
  lib/structures/TextVoiceChannel.js
Labels: Discord

#1370 Improved max_concurrency aware ShardManager
  examples/sharding.js
  lib/Client.js
  lib/gateway/Shard.js
  lib/gateway/ShardManager.js
Labels: enhancement

#1367 fix(getGuildAuditLog): cache users & threads earlier
  lib/Client.js
Labels: bug

#1377 fix(messageUpdate): fix `oldMessage#mentions` type
  index.d.ts
  lib/gateway/Shard.js
Labels: docs, typings

#1383 fix(joinVoiceChannel): skip permission check if Member uncached
  lib/Client.js
Labels: bug

#1382 fix(ShardManager): refactor concurrency check, add option
  index.d.ts
  lib/Client.js
  lib/gateway/ShardManager.js
Labels: bug, enhancement

#1376 fix(createRole): split options into separate overloads
  index.d.ts
Labels: enhancement, typings

#1363 feat(getGuildBans): support pagination
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: Discord

#1328 feat(editChannelPositions): add support for endpoint
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: enhancement, Discord

#1319 fix(editChannel): update options to match Discord docs
  index.d.ts
  lib/Client.js
  lib/structures/GuildChannel.js
Labels: enhancement

#1283 feat(connect): add token check
  lib/Client.js
Labels: hacktoberfest-accepted

#1388 feat(Client): allow custom numbers in intents option
  index.d.ts
  lib/Client.js
Labels: enhancement
