Repository abalabahaha/eris, pull requests merged in 2022-04, with the labels that each got.

#1303 chore(typings): reorganise
  index.d.ts
Labels: typings

#1245 Fix status
  index.d.ts
Labels: Discord, potential bug

#1364 fix(gateway): fix zlib data error
  lib/gateway/Shard.js
Labels: bug

#1361 fix(typings): Added "proxy_url" to EmbedVideo
  index.d.ts
Labels: typings
