Repository abalabahaha/eris, pull requests merged in 2022-03, with the labels that each got.

#1340 Add position to `CreateChannelOptions`
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
Labels: enhancement

#1339 Use maxShards instead of lastShardID
  lib/structures/Guild.js
Labels: enhancement, potential bug

#1345 Presence update ratelimit
  lib/gateway/Shard.js
Labels: Discord

#1323 fix(voice): avoid bitwise overflow error
  lib/voice/SharedStream.js
  lib/voice/VoiceConnection.js
Labels: bug
