Repository abalabahaha/eris, pull requests merged in 2022-02, with the labels that each got.

#1306 m.presence can be null in THREAD_MEMBERS_UPDATE
  lib/gateway/Shard.js
Labels: bug

#1311 Fix typing for `Message.createThreadWithMessage`
  index.d.ts
Labels: typings

#1313 fix(Member): User property reference
  lib/structures/Member.js
Labels: bug

#1326 Fix the casing for owner_id
  lib/structures/ThreadChannel.js
Labels: bug

#1305 fix(typings): add static keyword for Interaction.from
  index.d.ts
Labels: bug, typings

#1314 fix(interactions): Missing file redirect in createMessage
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/UnknownInteraction.js
Labels: bug

#1325 fix(slash): Snake case defaultPermissions to payload
  lib/Client.js
Labels: bug
