Repository abalabahaha/eris, pull requests merged in 2024-06, with the labels that each got.

#1486 feat(MediaChannels): Support Media Channels
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/ForumChannel.js
  lib/structures/Guild.js
  lib/structures/GuildChannel.js
  lib/structures/MediaChannel.js
  lib/structures/PublicThreadChannel.js
Labels: Discord

#1500 Added missing createdAt prop from Interaction's docs
  lib/structures/Interaction.js
Labels: farming, docs

#1505 fix(voice): OggOpusTransformer missing callback in _final
  lib/voice/streams/OggOpusTransformer.js
Labels: bug, voice

#1509 fix(exports): Remove old wildcard export
  package.json
Labels: farming

#1511 Fix: Old channel permission overwrites being overwritten
  lib/structures/CategoryChannel.js
  lib/structures/MediaChannel.js
  lib/structures/TextChannel.js
  lib/structures/VoiceChannel.js
Labels: bug
