Repository abalabahaha/eris, pull requests merged in 2024-07, with the labels that each got.

#1501 remove localized system message handling
  lib/structures/Message.js
Labels: enhancement

#1448 feat(voice): support resuming voice connection
  index.d.ts
  lib/voice/VoiceConnection.js
Labels: enhancement, Discord

#1487 feat: Role connections & subscriptions
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/rest/Endpoints.js
  lib/structures/Message.js
Labels: Discord

#1497 feat(ThreadChannel): Thread member pagination
  index.d.ts
  lib/Client.js
  lib/structures/ThreadChannel.js
  lib/structures/ThreadMember.js
Labels: Discord

#1470 feat(Reactions): Support super reactions
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/DMChannel.js
  lib/structures/GuildTextableChannel.js
  lib/structures/Message.js
Labels: Discord

#1496 feat(VoiceChannel): Support voice channel statuses
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/VoiceChannel.js
Labels: Discord

#1493 feat: Support polls
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/DMChannel.js
  lib/structures/GuildTextableChannel.js
  lib/structures/Message.js
  lib/structures/ModalSubmitInteraction.js
  lib/structures/UnknownInteraction.js
Labels: Discord

#1523 feat(Constants): Add GIF sticker format
  index.d.ts
  lib/Constants.js
Labels: Discord, farming
