Repository abalabahaha/eris, pull requests merged in 2024-08, with the labels that each got.

#1524 typings: Improvements and fixes
  index.d.ts
Labels: typings

#1525 fix(Member): fix voice state not updated when `member` field is missing.
  lib/structures/Member.js
Labels: bug

#1338 Remove all user account features
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Call.js
  lib/structures/DMChannel.js
  lib/structures/Guild.js
  lib/structures/GuildIntegration.js
  lib/structures/GuildTextableChannel.js
  lib/structures/Message.js
  lib/structures/Relationship.js
  lib/structures/User.js
  lib/structures/VoiceState.js
  lib/voice/VoiceConnection.js
Labels: Discord

#1533 Added the ability to edit the client's banner
  index.d.ts
  lib/Client.js
Labels: Discord

#1538 fix(User): defaultAvatar handling
  lib/structures/User.js
Labels: bug
