Repository abalabahaha/eris, pull requests merged in 2024-11, with the labels that each got.

#1581 fix(Interaction): set member id even when either the channel/guild isn't cached
  examples/components.js
  lib/structures/AutocompleteInteraction.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/ModalSubmitInteraction.js
  lib/structures/UnknownInteraction.js
Labels: bug

#1580 typings!: Remove empty string fields
  index.d.ts
Labels: Discord, docs, typings

#1579 chore(Member): Update member flags list
  lib/Constants.d.ts
  lib/Constants.js
Labels: Discord

#1578 docs(Interactions): Ability to create polls on deferred edit
  index.d.ts
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/ModalSubmitInteraction.js
  lib/structures/UnknownInteraction.js
Labels: Discord

#1577 feat(Role): Expose Get Guild Role endpoint
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/Role.js
Labels: Discord

#1576 feat(Stickers): Expose Get Sticker Pack endpoint
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
Labels: Discord

#1575 feat(Voice): Expose get guild user voice state endpoint
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/VoiceState.js
Labels: Discord

#1573 feat(Polls): Support Poll Result message
  index.d.ts
  lib/Constants.d.ts
  lib/Constants.js
Labels: Discord

#1572 chore(Constants): PURCHASE_NOTIFICATION message type
  lib/Constants.d.ts
  lib/Constants.js
Labels: Discord

#1571 feat(Permissions): Expose useExternalApps permission
  lib/Constants.d.ts
  lib/Constants.js
Labels: Discord

#1570 docs(Message): Document Message.call
  index.d.ts
  lib/structures/Message.js
Labels: Discord, docs

#1556 feat(Automod)!: Add missing features
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.d.ts
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/AutoModerationRule.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
Labels: Discord
