Repository abalabahaha/eris, pull requests merged in 2024-01, with the labels that each got.

#1285 Rework file attachments
  index.d.ts
  lib/Client.js
  lib/rest/RequestHandler.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/Message.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
  lib/structures/TextVoiceChannel.js
  lib/structures/ThreadChannel.js
  lib/structures/UnknownInteraction.js
Labels: enhancement, Discord, hacktoberfest-accepted

#1371 feat(gateway/REST): V10 API changes
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/rest/Endpoints.js
  lib/rest/RequestHandler.js
  lib/structures/TextChannel.js
Labels: Discord

#1276 Use process warnings for deprecations
  lib/Client.js
  lib/structures/Member.js
  lib/structures/PrivateChannel.js
  lib/util/emitDeprecation.js
Labels: enhancement

#1401 fix(types): somes types error
  index.d.ts
Labels: typings

#1465 fix(Client): wrong request url in editGuildWidget
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: bug

#1430 feat(bans): Seconds Support
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
  lib/structures/Member.js
  lib/util/emitDeprecation.js
Labels: enhancement, Discord

#1457 Type Error(Client.js)
  lib/Client.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/UnknownInteraction.js
Labels: docs

#1416 feat(Widget): support get image URL of widget
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: Discord

#1455 Acceptance of all alphabetic characters in slash commands.
  lib/Client.js
Labels: bug

#1372 feat(permissions): Slash Permissions v2
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/ApplicationCommand.js
  lib/structures/Guild.js
  lib/util/emitDeprecation.js
Labels: Discord

#1453 feat(permissions): Support new permissions 1 << 41-46
  index.d.ts
  lib/Constants.js
Labels: Discord

#1431 refactor(createChannel): reduce overloads from 30 to 6
  index.d.ts
Labels: farming, typings

#1467 fix(typings): Member.communicationDisabledUntil optional
  index.d.ts
Labels: typings

#1433 chore(StoreChannel): Store Channels No Longer Exist
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/GuildChannel.js
  lib/structures/StoreChannel.js
Labels: Discord

#1021 Return void on 204
  lib/rest/RequestHandler.js
Labels: enhancement

#1469 Various docs/typings enhancements and corrections
  .eslintrc.yml
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/gateway/Shard.js
  lib/gateway/ShardManager.js
  lib/rest/RequestHandler.js
  lib/structures/ApplicationCommand.js
  lib/structures/AutocompleteInteraction.js
  lib/structures/Base.js
  lib/structures/Call.js
  lib/structures/CategoryChannel.js
  lib/structures/Channel.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/ExtendedUser.js
  lib/structures/GroupChannel.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/GuildIntegration.js
  lib/structures/GuildPreview.js
  lib/structures/GuildScheduledEvent.js
  lib/structures/GuildTemplate.js
  lib/structures/Interaction.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/ModalSubmitInteraction.js
  lib/structures/NewsChannel.js
  lib/structures/NewsThreadChannel.js
  lib/structures/Permission.js
  lib/structures/PermissionOverwrite.js
  lib/structures/PingInteraction.js
  lib/structures/PrivateChannel.js
  lib/structures/PrivateThreadChannel.js
  lib/structures/PublicThreadChannel.js
  lib/structures/Relationship.js
  lib/structures/Role.js
  lib/structures/StageChannel.js
  lib/structures/StageInstance.js
  lib/structures/TextChannel.js
  lib/structures/TextVoiceChannel.js
  lib/structures/ThreadChannel.js
  lib/structures/ThreadMember.js
  lib/structures/UnavailableGuild.js
  lib/structures/UnknownInteraction.js
  lib/structures/User.js
  lib/structures/VoiceChannel.js
  lib/structures/VoiceState.js
  lib/util/BrowserWebSocket.js
  lib/util/Bucket.js
  lib/util/Collection.js
  lib/util/SequentialBucket.js
  lib/voice/SharedStream.js
  lib/voice/VoiceConnection.js
  lib/voice/VoiceDataStream.js
  package.json
Labels: enhancement, farming, docs, typings

#1428 feat(AutoModeration): Support Auto Moderation
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
  lib/structures/Message.js
Labels: Discord

#1473 feat(Guild): Edit MFA level
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
Labels: Discord

#1475 feat(Presence): Allow bots to set custom status
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
Labels: Discord

#1478 feat: Guild Onboarding
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/rest/Endpoints.js
  lib/structures/Guild.js
  lib/structures/Member.js
Labels: Discord

#1471 feat(User): Support avatar decorations
  index.d.ts
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/Member.js
  lib/structures/User.js
Labels: Discord

#1481 feat(gw): guildAuditLogEntryCreate event
  index.d.ts
  lib/gateway/Shard.js
Labels: Discord

#1482 fix(TextChannel): nsfw channel handling
  index.d.ts
  lib/structures/GuildChannel.js
  lib/structures/NewsChannel.js
  lib/structures/TextChannel.js
Labels: bug

#1483 fix(ApplicationCommandCreateOptions): correct type parameter
  index.d.ts
Labels: docs
