Repository abalabahaha/eris, pull requests merged in 2025-09, with the labels that each got.

#1602 chore: Add copilot instructions
  .github/copilot-instructions.md
Labels: farming

#1574 feat(GuildScheduledEvents): Expose recurrence rule functionality
  index.d.ts
  lib/Client.js
  lib/Constants.d.ts
  lib/Constants.js
  lib/structures/Guild.js
  lib/structures/GuildScheduledEvent.js
Labels: Discord

#1584 chore(gitignore): Add lock files for yarn,pnpm,bun
  .gitignore
Labels: farming

#1588 Fix: requires of translations for all locales.
  index.d.ts
Labels: typings

#1594 feat: Support Pin Messages permission
  lib/Constants.d.ts
  lib/Constants.js
Labels: Discord
